LAYER_DEFAULT:
  id: 3f06893f-3041-4ac4-b6b9-ae5053727098
  name: BoxEnhancerModel
  type: MODEL_CLASS
LAYER_CONTENT_LOADER:
  entry: index
  export: default
LAYER_NAMESPACE_CONFIG:
  name: boxEnhancer
LAYER_EDITOR_PROPS_VALUE_MODIFIER:
  content:
    type: editable
  style:
    type: editable
  children:
    type: hidden
  parentId:
    type: hidden
  id:
    type: hidden
