LAYER_DEFAULT:
  id: 8b230e60-53cc-4a65-85aa-7b5ccb5f5a9f
  name: withHandler
  type: HOC_CLASS
LAYER_CONTENT_LOADER:
  entry: index
  export: default
LAYER_EDITOR_PROPS_VALUE_MODIFIER:
  handlerName:
    type: editable
  handlerRefId:
    type: reference
